name: build and push development
#on: [push] # When pushing to any branch then run this action
on:
  push:
    branches: 
         - development
jobs:
  dev-build-push:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    environment: demo-workflow
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./dev/backend.Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:be-development
    
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: ./dev/frontend.Dockerfile
        push: true
        #test multiple tags with same docker file.
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:fe-development, ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:others